### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by mertbaba62** [Gumballton/calculator-meme-reels#1]
Hello. I'm quite unfamiliar with these issues, but I tried to open it correctly up to a point, but when I start the application, I get an error like this. What am I doing wrong? :

```python

``` File "C:\Users\mertd\OneDrive\Masaüstü\fastapi\main.py", line 1
    uvicorn main:app --reloadfrom fastapi import FastAPI, Request
            ^^^^
SyntaxError: invalid syntax

**Comment by Gumballton** [comment]
Hello, when you have done git clone to your folder, you need to install all the dependencies with the command pip install -r `requirements.txt`, and then run the application from the terminal with the command `uvicorn main:app --reload`
